SELECT CONCAT('Project' ,' ','') AS NAME, 
DATEDIFF(MONTH, START_DATA, FINISH_DATA) AS MONTH_COUNT
FROM project
WHERE DATEDIFF(MONTH, START_DATA, FINISH_DATA)
IN (
SELECT DATEDIFF(MONTH, START_DATA, FINISH_DATA)
FROM project
ORDER BY DATEDIFF(MONTH, START_DATA, FINISH_DATA) DESC
LIMIT 1
);
