SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM hw4d.worker
WHERE BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM hw4d.worker)
UNION
SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
FROM hw4d.worker
WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM hw4d.worker)