CREATE TABLE worker (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR NOT NULL
CHECK (CHAR_LENGTH(NAME)<=1000),
BIRTHDAY DATE CHECK(BIRTHDAY >= '1901-01-01'),
LEVEL VARCHAR NOT NULL
CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
SALARY INTEGER CHECK (SALARY >= 100 AND SALARY <=100000)
);
CREATE TABLE client (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR NOT NULL
CHECK (CHAR_LENGTH(NAME)<=1000)
);
CREATE TABLE project (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
CLIENT_ID INTEGER,
START_DATA DATE,
FINISH_DATA DATE
);
CREATE TABLE project_worker (
PROJECT_ID INTEGER,
WORKER_ID INTEGER,
FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
FOREIGN KEY (WORKER_ID) REFERENCES worker(ID),
PRIMARY KEY(PROJECT_ID, WORKER_ID)
);
